// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "data_service.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DataService } from "./data_service";
import type { EditsResponse } from "./data_service";
import type { EditsRequest } from "./data_service";
import type { StatsResponse } from "./data_service";
import type { StatsRequest } from "./data_service";
import type { SamplesResponse } from "./data_service";
import type { SamplesRequest } from "./data_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { QueryResponse } from "./data_service";
import type { QueryRequest } from "./data_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * DataService: a unified interface for all data operations
 *
 * @generated from protobuf service DataService
 */
export interface IDataServiceClient {
    /**
     * For  ordering, filtering and groupings.
     *
     * @generated from protobuf rpc: ApplyQuery
     */
    applyQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse>;
    /**
     * For individual/bulk inspection of content and stats.
     *
     * @generated from protobuf rpc: GetSamples
     */
    getSamples(input: SamplesRequest, options?: RpcOptions): UnaryCall<SamplesRequest, SamplesResponse>;
    /**
     * For overall data statistics.
     *
     * @generated from protobuf rpc: Statistics
     */
    statistics(input: StatsRequest, options?: RpcOptions): UnaryCall<StatsRequest, StatsResponse>;
    /**
     * For changing anything about a group of Samples: label, tag, presence.
     *
     * @generated from protobuf rpc: EditSample
     */
    editSample(input: EditsRequest, options?: RpcOptions): UnaryCall<EditsRequest, EditsResponse>;
}
/**
 * DataService: a unified interface for all data operations
 *
 * @generated from protobuf service DataService
 */
export class DataServiceClient implements IDataServiceClient, ServiceInfo {
    typeName = DataService.typeName;
    methods = DataService.methods;
    options = DataService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * For  ordering, filtering and groupings.
     *
     * @generated from protobuf rpc: ApplyQuery
     */
    applyQuery(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryRequest, QueryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * For individual/bulk inspection of content and stats.
     *
     * @generated from protobuf rpc: GetSamples
     */
    getSamples(input: SamplesRequest, options?: RpcOptions): UnaryCall<SamplesRequest, SamplesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SamplesRequest, SamplesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * For overall data statistics.
     *
     * @generated from protobuf rpc: Statistics
     */
    statistics(input: StatsRequest, options?: RpcOptions): UnaryCall<StatsRequest, StatsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatsRequest, StatsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * For changing anything about a group of Samples: label, tag, presence.
     *
     * @generated from protobuf rpc: EditSample
     */
    editSample(input: EditsRequest, options?: RpcOptions): UnaryCall<EditsRequest, EditsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditsRequest, EditsResponse>("unary", this._transport, method, opt, input);
    }
}
